config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts do
    resources :like_posts, only: %i[create destroy]
    resources :comments, only: %i[create] do
      resources :like_comments, only: %i[create destroy]
    end
  end
  resources :users, only: %I[index show]
  get 'friendships/create'
  get 'friendships/destroy'
  get 'friendships/update' => 'friendships#update', status: :accepted
  get 'friendships/edit' => 'friendships#edit', status: :reject
  # resources :friendships, only: %i[create destroy update]
  # get 'users/index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :like_comments, dependent: :destroy

  validates :post, presence: true
  validates :content, presence: true, length: { maximum: 255 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @comments = Comment.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @comment.post
    else
      flash.now[:danger] = 'error'
      redirect_back(fallback_location: root_path)
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>
  <table>
    <thead>
      <tr>
        <th>Commented by</th>
        <th>Comment</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= comment.user.email %></td>
          <td><%= comment.content %></td>
          <td>
            <span >
              <% pre_like = comment.like_comments.find { |liked_comment| liked_comment.user_id == current_user.id} %>
              <% if pre_like %>
                <%= link_to 'Dislike', post_comment_like_comment_path(id: current_user.id, comment_id: comment.id, post_id: comment.post.id), method: :delete %>
              <% else %>
                <%= link_to 'Like', post_comment_like_comments_path(id: current_user.id, comment_id: comment.id, post_id: comment.post.id), method: :post %>
              <% end %>
            </span>
          </td>
        </tr>
    </tbody>
  </table>

  <% if comment.like_comments.count > 0 %>
    <table>
      <thead>
        <tr>
          <th>Likes <%= comment.like_comments.count %></th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody>
        <% comment.like_comments.each do | ul | %>
          <tr>
            <td>Liked by</td>
            <td><%= ul.user.email %></td>
            <td><%= link_to 'Show', ul.user %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>