config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts do
    resources :like_posts, only: %i[create destroy]
    resources :comments, only: %i[create] do
      resources :like_comments, only: %i[create destroy]
    end
  end
  resources :users, only: %I[index show]
  get 'friendships/create'
  get 'friendships/destroy'
  get 'friendships/update' => 'friendships#update', status: :accepted
  get 'friendships/edit' => 'friendships#edit', status: :reject
  # resources :friendships, only: %i[create destroy update]
  # get 'users/index'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :liked_posts, dependent: :destroy
  has_many :like_comments, dependent: :destroy
  has_many :comments

  friendship_scope = -> { includes(:requester, :requestee).order('users.id') }
  has_many :following_friends, friendship_scope, foreign_key: 'requester_id', class_name: :Friendship
  has_many :followers_friends, friendship_scope, foreign_key: 'requestee_id', class_name: :Friendship

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  # Requests made by others to current_user
  def active_followers
    followers_friends.where(status: :accepted).map(&:requester)
  end

  def pending_followers
    followers_friends.where(status: :pending).map(&:requester)
  end

  # Requests made by current_user to others
  def pending_following
    following_friends.where(status: :pending).map(&:requestee)
  end

  def active_following
    following_friends.where(status: :accepted).map(&:requestee)
  end

  def rejected_followings
    following_friends.where(status: :rejected).map(&:requestee)
  end

  def rejected_followers
    followers_friends.where(status: :rejected).map(&:requester)
  end

  def feed
    followers_friends.where(status: :accepted).map(&:requester_id)
  end

  def remove_friendship(friend_id)
    following_friends.find_by_requestee_id(friend_id)&.destroy ||
      followers_friends.find_by_requester_id(friend_id)&.destroy
  end

  def friends_and_own_posts
    (Post.where(user: feed) + Post.where(user: id)).sort_by(&:updated_at)
    # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.password_confirmation = user.password
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.find_or_create_by_omniauth(auth_hash)
    where(email: auth_hash['info']['email']).first_or_create do |u|
      u.password = SecureRandom.hex
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @following = current_user.active_following
    @followers = current_user.active_followers
    @pending_followers = current_user.pending_followers
    @all_users = (@users - @following - @followers - @pending_followers - [current_user]).sort_by(&:id)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% content_for :header_h1 do %>
  <h1 class="fakebook">Users 🙋</h1>
<% end %>

<main class="users-container">
  <%= content_tag :h2, 'Pending requests' if current_user.pending_followers.any? %>
  <% @pending_followers.each do |pending_follower| %>
    <div class="user-profile">
      <div class="profile">
        <%= render 'users/partials/user_profile', user: pending_follower, link: true %>
      </div>
      <div class="comments">
        <%= link_to 'Accept', friendships_update_path(requester_id: pending_follower.id), class: 'option-button' %>
        <%= link_to 'Reject', friendships_edit_path(requester_id: pending_follower.id), class: 'option-button' %>
      </div>
    </div>
  <% end %>
  <%= content_tag :h2, 'Following' if (@following).any? %>
  <% @following.sort_by(&:id).each do |user| %>
    <div class="user-profile">
      <div class="profile">
        <%= render 'users/partials/user_profile', user: user, link: true %>
      </div>
      <div class="comments">
        <%= link_to 'Remove friendship', friendships_destroy_path(requestee_id: user.id), class: 'option-button'  %>
      </div>
    </div>
  <% end %>
  <%= content_tag :h2, 'All users' if @all_users.any? %>
  <% @all_users.each do |user| %>
    <div class="user-profile">
      <div class="profile">
        <%= render 'users/partials/user_profile', user: user, link: true %>
      </div>
      <div class="comments">
        <% if current_user.pending_following.include? user %>
          <span class="request-pending">Request pending...</span>
          <%= link_to 'Cancel request', friendships_destroy_path(requestee_id: user.id), class: 'option-button'  %>
        <% elsif current_user.rejected_followings.include?(user) || current_user.rejected_followers.include?(user) %>
          <span class="">Request rejected!</span>
          <%= link_to 'Remove request', friendships_destroy_path(requestee_id: user.id), class: 'option-button'  %>
        <% else %>
          <%= link_to 'Send request', friendships_create_path(requestee_id: user.id), class: 'option-button'  %>
        <% end %>
      </div>
    </div>
  <% end %>
</main>

app/views/users/show.html.erb
<p>Email: <%= @user.email %></p>

<% if @user.posts.count > 0 %>
  <table> User Posts
    <thead>
      <tr>
        <th>Content</th>
        <th>Created at</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <% @user.posts.each do | post | %>
        <tr>
          <td><%= post.content %></td>
          <td><%= post.created_at %></td>
          <td><%= link_to 'Show', post %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if @user.liked_posts.count > 0 %>
  <table> Liked posts
    <thead>
      <tr>
        <th>Content</th>
        <th>Created at</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <% @user.liked_posts.each do | lp | %>
        <tr>
          <td><%= lp.post.content %></td>
          <td><%= lp.post.created_at %></td>
          <td><%= link_to 'Show', lp.post %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Back', users_path %>