config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts do
    resources :like_posts, only: %i[create destroy]
    resources :comments, only: %i[create] do
      resources :like_comments, only: %i[create destroy]
    end
  end
  resources :users, only: %I[index show]
  get 'friendships/create'
  get 'friendships/destroy'
  get 'friendships/update' => 'friendships#update', status: :accepted
  get 'friendships/edit' => 'friendships#edit', status: :reject
  # resources :friendships, only: %i[create destroy update]
  # get 'users/index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :liked_posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :content, presence: true, length: { in: 1..1500 }
  validates :user, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %I[show edit update destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.friends_and_own_posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def find_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= form_for([@post, @post.comments.build]) do |p| %>
  <%= p.label :comment %>
  <%= p.text_area :content, class: "form-control" %>
  <%= p.hidden_field :post_id %>
  <%= p.submit 'Submit', class: "btn btn-primary" %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <%= render 'shared/error_messages', object: form.object %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Content</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.email %></td>
        <td><%= post.content %></td>
        <td><%= post.user.email %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <span >
            <% pre_like = post.liked_posts.find { |liked_post| liked_post.user_id == current_user.id} %>
            <% if pre_like %>
              <%= link_to 'Dislike', post_like_post_path(id: current_user.id, post_id: post.id), method: :delete %>
            <% else %>
              <%= link_to 'Like', post_like_posts_path(id: current_user.id, post_id: post.id), method: :post %>
            <% end %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post for <%= current_user.email %></h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<% if @post.liked_posts.count > 0 %>
  <table>
    <thead>
      <tr>
        <th>Likes <%= @post.liked_posts.count %></th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <% @post.liked_posts.each do | ul | %>
        <tr>
          <td>Liked by</td>
          <td><%= ul.user.email %></td>
          <td><%= link_to 'Show', ul.user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<p>
  <strong>Email:</strong>
  <%= @post.user.email %>
</p>

<%= render 'comments/comment' %>

<%= render 'comment_form' %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>